//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.27 at 03:04:18 PM EDT 
//


package gov.nasa.jpf.regression.block.jaxbiface;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="className" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="computeMetaData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}globalVarNotEqual" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}initializationBlockSummary" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}methodSummary" maxOccurs="unbounded"/>
 *         &lt;element ref="{}classSummary" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "className",
    "computeMetaData",
    "globalVarNotEqual",
    "initializationBlockSummary",
    "methodSummary",
    "classSummary"
})
@XmlRootElement(name = "classSummary")
public class ClassSummary {

    @XmlElement(required = true)
    protected String className;
    @XmlElement(required = true)
    protected String computeMetaData;
    protected List<GlobalVarNotEqual> globalVarNotEqual;
    protected List<InitializationBlockSummary> initializationBlockSummary;
    @XmlElement(required = true)
    protected List<MethodSummary> methodSummary;
    protected List<ClassSummary> classSummary;

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the computeMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComputeMetaData() {
        return computeMetaData;
    }

    /**
     * Sets the value of the computeMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComputeMetaData(String value) {
        this.computeMetaData = value;
    }

    /**
     * Gets the value of the globalVarNotEqual property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the globalVarNotEqual property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGlobalVarNotEqual().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GlobalVarNotEqual }
     * 
     * 
     */
    public List<GlobalVarNotEqual> getGlobalVarNotEqual() {
        if (globalVarNotEqual == null) {
            globalVarNotEqual = new ArrayList<GlobalVarNotEqual>();
        }
        return this.globalVarNotEqual;
    }

    /**
     * Gets the value of the initializationBlockSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initializationBlockSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitializationBlockSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InitializationBlockSummary }
     * 
     * 
     */
    public List<InitializationBlockSummary> getInitializationBlockSummary() {
        if (initializationBlockSummary == null) {
            initializationBlockSummary = new ArrayList<InitializationBlockSummary>();
        }
        return this.initializationBlockSummary;
    }

    /**
     * Gets the value of the methodSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the methodSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMethodSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MethodSummary }
     * 
     * 
     */
    public List<MethodSummary> getMethodSummary() {
        if (methodSummary == null) {
            methodSummary = new ArrayList<MethodSummary>();
        }
        return this.methodSummary;
    }

    /**
     * Gets the value of the classSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassSummary }
     * 
     * 
     */
    public List<ClassSummary> getClassSummary() {
        if (classSummary == null) {
            classSummary = new ArrayList<ClassSummary>();
        }
        return this.classSummary;
    }

}
