//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.27 at 03:04:18 PM EDT 
//


package gov.nasa.jpf.regression.block.jaxbiface;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="methodName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="origModifiers" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="origMethodParameters" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="origMethodParamTypes" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="origMethodReturnType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modModifiers" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="modMethodParameters" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="modMethodParamTypes" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="modMethodReturnType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultConstructorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="matched" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="equivalent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element ref="{}blockInfo" maxOccurs="unbounded"/>
 *         &lt;element ref="{}classSummary" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "methodName",
    "origModifiers",
    "origMethodParameters",
    "origMethodParamTypes",
    "origMethodReturnType",
    "modModifiers",
    "modMethodParameters",
    "modMethodParamTypes",
    "modMethodReturnType",
    "defaultConstructorName",
    "matched",
    "equivalent",
    "blockInfo",
    "classSummary"
})
@XmlRootElement(name = "methodSummary")
public class MethodSummary {

    @XmlElement(required = true)
    protected String methodName;
    protected List<String> origModifiers;
    protected List<String> origMethodParameters;
    protected List<String> origMethodParamTypes;
    @XmlElement(required = true)
    protected String origMethodReturnType;
    protected List<String> modModifiers;
    protected List<String> modMethodParameters;
    protected List<String> modMethodParamTypes;
    @XmlElement(required = true)
    protected String modMethodReturnType;
    protected String defaultConstructorName;
    protected boolean matched;
    protected boolean equivalent;
    @XmlElement(required = true)
    protected List<BlockInfo> blockInfo;
    protected List<ClassSummary> classSummary;

    /**
     * Gets the value of the methodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * Sets the value of the methodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodName(String value) {
        this.methodName = value;
    }

    /**
     * Gets the value of the origModifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the origModifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrigModifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOrigModifiers() {
        if (origModifiers == null) {
            origModifiers = new ArrayList<String>();
        }
        return this.origModifiers;
    }

    /**
     * Gets the value of the origMethodParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the origMethodParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrigMethodParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOrigMethodParameters() {
        if (origMethodParameters == null) {
            origMethodParameters = new ArrayList<String>();
        }
        return this.origMethodParameters;
    }

    /**
     * Gets the value of the origMethodParamTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the origMethodParamTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrigMethodParamTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOrigMethodParamTypes() {
        if (origMethodParamTypes == null) {
            origMethodParamTypes = new ArrayList<String>();
        }
        return this.origMethodParamTypes;
    }

    /**
     * Gets the value of the origMethodReturnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigMethodReturnType() {
        return origMethodReturnType;
    }

    /**
     * Sets the value of the origMethodReturnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigMethodReturnType(String value) {
        this.origMethodReturnType = value;
    }

    /**
     * Gets the value of the modModifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modModifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModModifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getModModifiers() {
        if (modModifiers == null) {
            modModifiers = new ArrayList<String>();
        }
        return this.modModifiers;
    }

    /**
     * Gets the value of the modMethodParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modMethodParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModMethodParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getModMethodParameters() {
        if (modMethodParameters == null) {
            modMethodParameters = new ArrayList<String>();
        }
        return this.modMethodParameters;
    }

    /**
     * Gets the value of the modMethodParamTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modMethodParamTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModMethodParamTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getModMethodParamTypes() {
        if (modMethodParamTypes == null) {
            modMethodParamTypes = new ArrayList<String>();
        }
        return this.modMethodParamTypes;
    }

    /**
     * Gets the value of the modMethodReturnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModMethodReturnType() {
        return modMethodReturnType;
    }

    /**
     * Sets the value of the modMethodReturnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModMethodReturnType(String value) {
        this.modMethodReturnType = value;
    }

    /**
     * Gets the value of the defaultConstructorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultConstructorName() {
        return defaultConstructorName;
    }

    /**
     * Sets the value of the defaultConstructorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultConstructorName(String value) {
        this.defaultConstructorName = value;
    }

    /**
     * Gets the value of the matched property.
     * 
     */
    public boolean isMatched() {
        return matched;
    }

    /**
     * Sets the value of the matched property.
     * 
     */
    public void setMatched(boolean value) {
        this.matched = value;
    }

    /**
     * Gets the value of the equivalent property.
     * 
     */
    public boolean isEquivalent() {
        return equivalent;
    }

    /**
     * Sets the value of the equivalent property.
     * 
     */
    public void setEquivalent(boolean value) {
        this.equivalent = value;
    }

    /**
     * Gets the value of the blockInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blockInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlockInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BlockInfo }
     * 
     * 
     */
    public List<BlockInfo> getBlockInfo() {
        if (blockInfo == null) {
            blockInfo = new ArrayList<BlockInfo>();
        }
        return this.blockInfo;
    }

    /**
     * Gets the value of the classSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassSummary }
     * 
     * 
     */
    public List<ClassSummary> getClassSummary() {
        if (classSummary == null) {
            classSummary = new ArrayList<ClassSummary>();
        }
        return this.classSummary;
    }

}
