//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.27 at 03:04:18 PM EDT 
//


package gov.nasa.jpf.regression.block.jaxbiface;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nasa.jpf.regression.block.jaxbiface package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nasa.jpf.regression.block.jaxbiface
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InitializationBlockSummary }
     * 
     */
    public InitializationBlockSummary createInitializationBlockSummary() {
        return new InitializationBlockSummary();
    }

    /**
     * Create an instance of {@link BlockInfo }
     * 
     */
    public BlockInfo createBlockInfo() {
        return new BlockInfo();
    }

    /**
     * Create an instance of {@link BlockSummary }
     * 
     */
    public BlockSummary createBlockSummary() {
        return new BlockSummary();
    }

    /**
     * Create an instance of {@link ClassSummary }
     * 
     */
    public ClassSummary createClassSummary() {
        return new ClassSummary();
    }

    /**
     * Create an instance of {@link GlobalVarNotEqual }
     * 
     */
    public GlobalVarNotEqual createGlobalVarNotEqual() {
        return new GlobalVarNotEqual();
    }

    /**
     * Create an instance of {@link MethodSummary }
     * 
     */
    public MethodSummary createMethodSummary() {
        return new MethodSummary();
    }

}
